use same test image builder scripts on travis/github

diff --git a/ci/deploy/dockerhub-test-images b/ci/deploy/dockerhub-test-images
--- a/ci/deploy/dockerhub-test-images
+++ b/ci/deploy/dockerhub-test-images
@@ -3,26 +3,33 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-# these variable must be available securely from CI
+# check needed variables are defined
+if [ ! -v DOCKER_USERNAME ] ||\
+    [ ! -v DOCKER_PASSWORD ] ||\
+    [ ! -v DOCKER_REGISTRY ]; then
+    echo "## ERROR: Please define the environs (DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_REGISTRY) in your CI settings!"
+    exit 1
+fi
+
+# check script needed variables
+if [ ! -v OWNER ] || [ ! -v TAG_PREFIX ] || [ ! -v GIT_TAG ]; then
+    echo "## ERROR: incorrect use of script. OWNER (e.g. itisfoundation or user) and/or TAG_PREFIX (e.g. master, staging), and/or GIT_TAG not defined!"
+    exit 1
+fi
+
+# these variable must be available securely from the CI
 echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+
 # only upstream is allowed to push to itisfoundation repo
-current_fork=$(echo "${TRAVIS_REPO_SLUG%/*}" | tr '[:upper:]' '[:lower:]')
-if [ $current_fork != "itisfoundation" ] &&\
+if [ $OWNER != "itisfoundation" ] &&\
     ([ ! -v DOCKER_REGISTRY ] || [ -z $DOCKER_REGISTRY ] || [ "$DOCKER_REGISTRY" = "itisfoundation" ]); then
     echo "## ERROR: it is not allowed to push to the main dockerhub repository from a fork!"
     echo "## Please adapt your CI-defined environs (DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_REGISTRY)"
     exit 1
 fi
 
+# define the local image tag
 export DOCKER_IMAGE_TAG=$(exec ci/helpers/build_docker_image_tag)
-
-# tags cache and version befor pushing
-make tag-cache
-make tag-version
-
-# show current images on system
-echo "## Before push"
-make info-images
 
 # push the local cache
 make push-cache
