add similar checks on integration tests and system tests

diff --git a/.github/workflows/ci-testing-deploy.yml b/.github/workflows/ci-testing-deploy.yml
--- a/.github/workflows/ci-testing-deploy.yml
+++ b/.github/workflows/ci-testing-deploy.yml
@@ -1224,7 +1224,7 @@ jobs:
         run: |
           echo "::error title=ERROR::one of the unit-tests failed!"
           exit 1
-      - name: all the previous jobs were run successfully or skipped
+      - name: all the previous unit-tests were run successfully or skipped
         if: ${{ !contains(join(needs.*.result, ','), 'failure') }}
         run: echo "::notice All good!"
 
@@ -1543,8 +1543,15 @@ jobs:
       ]
     runs-on: ubuntu-latest
     steps:
-      - name: all unit tests were run or skipped
-        run: echo "all unit tests were run or skipped"
+      - name: a previous integration-test job failed
+        if: ${{ contains(join(needs.*.result, ','), 'failure') }}
+        run: |
+          echo "::error title=ERROR::one of the unit-tests failed!"
+          exit 1
+      - name: all the previous integration-tests were run successfully or skipped
+        if: ${{ !contains(join(needs.*.result, ','), 'failure') }}
+        run: echo "::notice All good!"
+
 
   system-test-public-api:
     needs: [changes, build-test-images]
@@ -1791,8 +1798,14 @@ jobs:
       ]
     runs-on: ubuntu-latest
     steps:
-      - name: all unit tests were run or skipped
-        run: echo "all unit tests were run or skipped"
+      - name: a previous system-test job failed
+        if: ${{ contains(join(needs.*.result, ','), 'failure') }}
+        run: |
+          echo "::error title=ERROR::one of the unit-tests failed!"
+          exit 1
+      - name: all the previous system-tests were run successfully or skipped
+        if: ${{ !contains(join(needs.*.result, ','), 'failure') }}
+        run: echo "::notice All good!"
 
   deploy:
     name: deploy to dockerhub
